apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: klbkoh5sx-nodejs 
  janus-idp.io/tekton: klbkoh5sx-nodejs
  backstage.io/kubernetes-id: klbkoh5sx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: klbkoh5sx-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml