apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: klbkoh5sx-nodejs
  janus-idp.io/tekton: klbkoh5sx-nodejs
  backstage.io/kubernetes-id: klbkoh5sx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: klbkoh5sx-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
